build_tag_release:
  image: greenaddress/android@sha256:c00c98afd6682d9a8e18917e75d1cfca24fa3b9575a783a9abaec826d8b23964
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 hour
    when: on_success
    paths:
    - app/build/outputs/apk/*/release/*.apk
    - app/build/outputs/mapping/productionRelease/mapping.txt
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./gradlew lintProductionRelease
    - ./gradlew assembleProductionRelease

build_debug:
  image: greenaddress/android@sha256:c00c98afd6682d9a8e18917e75d1cfca24fa3b9575a783a9abaec826d8b23964
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    when: on_success
    paths:
    - app/build/outputs/apk/*/debug/*.apk
    - app/build/outputs/mapping/*/debug/mapping.txt
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./gradlew lintProductionRelease
    - ./gradlew assembleProductionDebug

build_tag_osx_release:
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - ./gradlew lintProductionRelease
    - ./gradlew assembleProductionRelease

package_release:
  tags:
    - garelease
  stage: deploy
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    paths:
    - app/build/outputs/*
    when: on_success
  script: cd $CI_PROJECT_DIR/app/build/outputs/apk && /opt/process_release
  dependencies:
  - build_tag_release
